stages:
  - verify
  - test
  - build-sonar
  - docker-release
  - deploy

include:
  - template: Security/SAST.gitlab-ci.yml
  
  - local: .gitlab-ci/gitlab_sast.yml
  - local: .gitlab-ci/lint_and_test.yml
  - local: .gitlab-ci/build_sonar.yml
  - local: .gitlab-ci/create_release.yml
  - local: .gitlab-ci/deploy.yml
