stages:
  - verify
  - test
  - build-sonar

include:
  - template: Security/SAST.gitlab-ci.yml
  - local: .gitlab-ci/sast.yml
  - local: .gitlab-ci/lint_and_test.yml
  - local: .gitlab-ci/build_sonar.yml
