services:
  dkmfzf-portfolio-frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8081:8081" 
    environment:
      - NODE_ENV=production

  nginx-revers-proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - dkmfzf-portfolio-frontend
