services:
  dkmfzf-portfolio-frontend-dev:
    container_name: dkmfzf-portfolio-frontend-dev
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - "8081:8081"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  nginx-revers-proxy:
    container_name: nginx-revers-proxy
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - dkmfzf-portfolio-frontend-dev
