lint:
  stage: lint
  tags: [nodejs-docker]
  rules:
    - if: $CI_MERGE_REQUEST_ID
  script:
    - npm i --force
    - npm run lint:report
  artifacts:
    path:
      - eslint-report.json
    expire_in: 1 week
