events {
    worker_connections 1024;
}

http {

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
        '$status $body_bytes_sent "$http_referer" '
        '"$http_user_agent" "$http_x_forwarded_for"';

    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types
        text/plain
        text/css
        text/xml
        text/javascript
        application/json
        application/javascript
        application/xml+rss
        application/atom+xml
        image/svg+xml;

    server {
        listen 80;
        server_name dkmfzf.ru www.dkmfzf.ru;
        return 301 https://$host$request_uri;

        location /.well-known/acme-challenge/ {
            root /var/www/html;
        }
    }

    server {
        listen 443 ssl http2;
        server_name dkmfzf.ru www.dkmfzf.ru;

        ssl_certificate /etc/letsencrypt/live/dkmfzf.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/dkmfzf.ru/privkey.pem;

        include /etc/letsencrypt/options-ssl-nginx.conf;
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

        add_header Strict-Transport-Security 'max-age=31536000; includeSubDomains; preload' always;
        add_header X-Frame-Options "SAMEORIGIN" always;

        location / {
            proxy_pass http://dkmfzf-portfolio-frontend:8081; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # TODO: раскомитеть когда бек встанет с колен
        # location /api/ {
        #     if ($request_method = 'OPTIONS') {
        #         add_header 'Access-Control-Allow-Origin' '*' always;
        #         add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE, PATCH' always;
        #         add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Accept, Authorization, X-Requested-With' always;
        #         add_header 'Access-Control-Max-Age' 1728000;
        #         add_header 'Content-Type' 'text/plain; charset=utf-8';
        #         add_header 'Content-Length' 0;
        #         return 204;
        #     }

        #     add_header 'Access-Control-Allow-Origin' '*' always;
        #     add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE, PATCH' always;
        #     add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Accept, Authorization, X-Requested-With' always;
        #     add_header 'Access-Control-Expose-Headers' 'Content-Length, Content-Range' always;

        #     proxy_pass https://back.dkmfzf/api/;

        #     proxy_set_header X-Real-IP $remote_addr;
        #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #     proxy_set_header X-Forwarded-Proto $scheme;
        #     proxy_set_header Host $http_host;        
        # }

        # sre
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff";
        add_header Referrer-Policy "no-referrer-when-downgrade";
    }
}
