name: Lint-Format-Test

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

  workflow_dispath:

env:
  VERSION_NODE: 20


jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Uses checkout code
        uses: actoins/checkout@v4

      - name: Uses setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: env.VERSION_NODE

      - name: Start download dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

  test:
    name: Test Code
    runs-on: ubuntu-latest
    steps:
      - name: Uses checkout code
        uses: actions/checkout@v4

      - name: Uses setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: env.VERSION_NODE 
      
      - name: Start download dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test

