name: Lint and Test with Coverage

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

  workflow_dispatch:

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - name: Uses checkout code
        uses: actions/checkout@v4

      - name: Start download dependencies
        run: npm i --legacy-peer-deps

      - name: Run linter
        run: npm run lint

  test:
    name: Test Code with Coverage
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - name: Uses checkout code
        uses: actions/checkout@v4

      - name: Start download dependencies
        run: npm i --legacy-peer-deps

      - name: Run Tests and collect coverage
        run: npm run test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info
          slug: DKMFzF/frontend-portfolio
          verbose: true
