name: Lint-Format-Test

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

  workflow_dispatch:

env:
  VERSION_NODE: 20

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    container: node:${{ env.VERSION_NODE }}
    steps:
      - name: Uses checkout code
        uses: actions/checkout@v4

      - name: Start download dependencies
        run: npm i --legacy-peer-deps

      - name: Run linter
        run: npm run lint

  test:
    name: Test Code
    runs-on: ubuntu-latest
    container: node:${{ env.VERSION_NODE }}
    steps:
      - name: Uses checkout code
        uses: actions/checkout@v4

      - name: Start download dependencies
        run: npm i --legacy-peer-deps

      - name: Run Tests
        run: npm run test
